Develop
Evgenia789/bot_personal_expenses pull request #3
Opened 2023-04-23 12:51 UTC by Evgenia789

Authorization

2023-04-29 07:00 UTC, atsanda requested changes
A small optimization is required

2023-04-29 07:00 UTC, atsanda commented on src/tgbot_expenses/models/expense_tracking_models.py
> +    telegram_id = sa.Column(sa.BigInteger, nullable=False)
In principle, you don't need this model at all. Here you map telegram_id to internal id, that's it. But it leads to unnecessary overhead when you retrieve User based on his telegram_id. Unless there was a good reason behind this solution, I suggest to remove this model and use `telegram_user_id` directly in `Category` Account` `Expense` `Income`

2023-04-29 07:00 UTC, atsanda commented on src/tgbot_expenses/models/expense_tracking_models.py
> +    telegram_id = sa.Column(sa.BigInteger, nullable=False)
You can justify this model if you say that you plan to further extend it, with photos, for example. From this perspective, it has a right to exist, but you any way need to use telegram_id as a primary key. 
For example,
```python
class User(Base):
    id = sa.Column(sa.Integer, primary_key=True, index=True)
```
and then, when you create pass telegram_id as an id.
```python
        user = User(id=telegram_id)
        session.add(user)
```

2023-04-29 07:00 UTC, atsanda commented on src/tgbot_expenses/services/account_service.py
> +        user_id = await get_user_id(telegram_id=telegram_id)
you don't need this if you use telegram_id as an id for your internal user model

2023-04-29 07:00 UTC, atsanda commented on src/tgbot_expenses/services/account_service.py
> +        user_id = await get_user_id(telegram_id=telegram_id)
you don't need this if you use telegram_id as an id for your internal user model

2023-04-29 07:00 UTC, atsanda commented on src/tgbot_expenses/services/account_service.py
> +        user_id = await get_user_id(telegram_id=telegram_id)
you don't need this if you use telegram_id as an id for your internal user model

2023-04-29 07:00 UTC, atsanda commented on src/tgbot_expenses/services/account_service.py
> +            user_id = await get_user_id(telegram_id=telegram_id)
you don't need this if you use telegram_id as an id for your internal user model

2023-04-29 07:00 UTC, atsanda commented on src/tgbot_expenses/services/category_service.py
> +        user_id = await get_user_id(telegram_id=telegram_id)
you don't need this if you use telegram_id as an id for your internal user model

2023-04-29 07:00 UTC, atsanda commented on src/tgbot_expenses/services/category_service.py
> +        user_id = await get_user_id(telegram_id=telegram_id)
you don't need this if you use telegram_id as an id for your internal user model

2023-04-29 07:00 UTC, atsanda commented on src/tgbot_expenses/services/category_service.py
> +        user_id = await get_user_id(telegram_id=telegram_id)
you don't need this if you use telegram_id as an id for your internal user model

2023-04-29 07:00 UTC, atsanda commented on src/tgbot_expenses/services/category_service.py
> +        user_id = await get_user_id(telegram_id=telegram_id)
you don't need this if you use telegram_id as an id for your internal user model

2023-04-29 07:00 UTC, atsanda commented on src/tgbot_expenses/services/expense_service.py
> +        user_id = await get_user_id(telegram_id=telegram_id)
you don't need this if you use telegram_id as an id for your internal user model

2023-04-29 07:00 UTC, atsanda commented on src/tgbot_expenses/services/expense_service.py
> +        user_id = await get_user_id(telegram_id=telegram_id)
you don't need this if you use telegram_id as an id for your internal user model

2023-04-29 07:00 UTC, atsanda commented on src/tgbot_expenses/services/income_service.py
> +        user_id = await get_user_id(telegram_id=telegram_id)
you don't need this if you use telegram_id as an id for your internal user model

2023-04-29 07:00 UTC, atsanda commented on src/tgbot_expenses/utils/queries_database.py
> +async def get_all_accounts_with_retry(telegram_id: int,
that's actually a good place to use decorators
retry logic is agnostic of the actual action you man to implement. It would be more readable to write
```python
@retry(max_retries=3, retry_delay=60)
def get_all_accounts_with_retry(telegram_id: int):
    accounts = await get_all_accounts(telegram_id=telegram_id)
    return accounts
```

2023-04-29 07:00 UTC, atsanda commented on src/tgbot_expenses/models/expense_tracking_models.py
> +    telegram_id = sa.Column(sa.BigInteger, nullable=False)
Okay, I see, you use it for `/init`. Then you could keep the model with the primary key I mentioned above.

2023-04-30 16:11 UTC, Evgenia789 commented on src/tgbot_expenses/models/expense_tracking_models.py
> +    telegram_id = sa.Column(sa.BigInteger, nullable=False)
I fixed it.

2023-04-30 16:11 UTC, Evgenia789 commented on src/tgbot_expenses/services/account_service.py
> +        user_id = await get_user_id(telegram_id=telegram_id)
I fixed it.

2023-04-30 16:11 UTC, Evgenia789 commented on src/tgbot_expenses/services/account_service.py
> +        user_id = await get_user_id(telegram_id=telegram_id)
I fixed it

2023-04-30 16:11 UTC, Evgenia789 commented on src/tgbot_expenses/services/account_service.py
> +        user_id = await get_user_id(telegram_id=telegram_id)
I fixed it

2023-04-30 16:11 UTC, Evgenia789 commented on src/tgbot_expenses/services/account_service.py
> +            user_id = await get_user_id(telegram_id=telegram_id)
I fixed it

2023-04-30 16:12 UTC, Evgenia789 commented on src/tgbot_expenses/services/category_service.py
> +        user_id = await get_user_id(telegram_id=telegram_id)
I fixed it

2023-04-30 16:12 UTC, Evgenia789 commented on src/tgbot_expenses/services/category_service.py
> +        user_id = await get_user_id(telegram_id=telegram_id)
I fixed it

2023-04-30 16:12 UTC, Evgenia789 commented on src/tgbot_expenses/services/category_service.py
> +        user_id = await get_user_id(telegram_id=telegram_id)
I fixed it

2023-04-30 16:12 UTC, Evgenia789 commented on src/tgbot_expenses/services/category_service.py
> +        user_id = await get_user_id(telegram_id=telegram_id)
I fixed it

2023-04-30 16:12 UTC, Evgenia789 commented on src/tgbot_expenses/services/expense_service.py
> +        user_id = await get_user_id(telegram_id=telegram_id)
I fixed it

2023-04-30 16:12 UTC, Evgenia789 commented on src/tgbot_expenses/services/expense_service.py
> +        user_id = await get_user_id(telegram_id=telegram_id)
I fixed it

2023-04-30 16:12 UTC, Evgenia789 commented on src/tgbot_expenses/services/income_service.py
> +        user_id = await get_user_id(telegram_id=telegram_id)
I fixed it

2023-04-30 16:12 UTC, Evgenia789 commented on src/tgbot_expenses/utils/queries_database.py
> +async def get_all_accounts_with_retry(telegram_id: int,
I fixed it

2023-05-06 06:09 UTC, atsanda approved these changes
One minor remark, otherwise good to go

2023-05-06 06:09 UTC, atsanda commented on src/tgbot_expenses/utils/retry_decorator.py
> +                    logging.error(f"Error getting accounts: {e}")
The error message should be be more general. It is not necessarily about accounts

2023-05-07 12:27 UTC, merged